# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
    pod 'AlamofireObjectMapper'
    pod 'SVProgressHUD'
    pod 'ReachabilitySwift'
end

target 'LocationCheck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocationCheck
  shared_pods
  
  target 'LocationCheckTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

  target 'LocationCheckUITests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

end
